## Copyright 2024 Kakusui LLC (https://kakusui.org) (https://github.com/Kakusui) (https://github.com/Kakusui/kakusui.org)
## Use of this source code is governed by an GNU Affero General Public License v3.0
## license that can be found in the LICENSE file.

FROM python:3.11.8-slim

WORKDIR /app

## Copy only requirements file first to leverage Docker cache
COPY requirements.txt .

## Install required Python packages
RUN pip install --no-cache-dir -r requirements.txt && \
    python -m spacy download ja_core_news_lg

## Install required packages (linux) including GPG
RUN apt-get update && \
    apt-get install -y --no-install-recommends gnupg2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

## Copy the rest of the application code
COPY . .

## Remove unnecessary files (keep .env)
RUN rm -rf __pycache__ Dockerfile.prod Dockerfile.dev entrypoint_prod.sh

## Make entrypoint script executable
RUN chmod +x entrypoint_dev.sh

ENV PYTHONPATH=/app

EXPOSE 5000

## Start the app
CMD ["./entrypoint_dev.sh"]